apiVersion: v1
kind: Service
metadata:
  name: kube-state-metrics
  namespace: monitoring
  labels:
    app.kubernetes.io/name: kube-state-metrics
spec:
  ports:
    - name: http-metrics
      port: 8484
      targetPort: 8484
    - name: telemetry
      port: 8485
      targetPort: 8485
  selector:
    app.kubernetes.io/name: kube-state-metrics
