apiVersion: v1
kind: ConfigMap
metadata:
  name: prometheus-config
data:
  prometheus.yml: |
    global:
      scrape_interval: 15s

    scrape_configs:
      - job_name: 'prometheus'
        static_configs:
          - targets: ['localhost:9090']

      - job_name: 'mktxp'
        static_configs:
          - targets: ['mktxp-exporter:49090']

      - job_name: 'vm-cluster-health'
        static_configs:
          - targets: 
              - 'vminsert-service:8480'
              - 'vmselect-service:8481'
              - 'vmstorage:8482'

    remote_write:
      - url: "http://vminsert-service:8480/insert/0/prometheus/api/v1/write"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: prometheus
spec:
  replicas: 1
  selector:
    matchLabels:
      app: prometheus
  template:
    metadata:
      labels:
        app: prometheus
    spec:
      containers:
      - name: prometheus
        image: prom/prometheus:latest
        args: ["--config.file=/etc/prometheus/prometheus.yml"]
        volumeMounts:
        - name: config
          mountPath: /etc/prometheus/
      volumes:
      - name: config
        configMap:
          name: prometheus-config