apiVersion: v1
kind: Service
metadata:
  name: vmstorage
spec:
  clusterIP: None
  ports:
    - port: 8400
      name: insert
    - port: 8401
      name: select
    - port: 8482
      name: http
  selector:
    app: vmstorage
