apiVersion: agent.k8s.elastic.co/v1alpha1
kind: Agent
metadata:
  name: otel-collector
  namespace: elastic-system
spec:
  version: 9.3.2
  kibanaRef:
    name: kibana
  fleetServerRef: 
    name: fleet-server
  mode: fleet
  policyID: eck-apm-otel-policy
  deployment:
    replicas: 1
    podTemplate:
      spec:
        containers:
          - name: agent
            env:
              - name: FLEET_INSECURE
                value: "true"
            ports:
              - containerPort: 8200
                name: apm-otlp
        volumes:
          - name: agent-data
            emptyDir: {}
