apiVersion: v1
kind: ServiceAccount
metadata:
  name: fleet-server
  namespace: elastic-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: fleet-server
rules:
- apiGroups: [""]
  resources: ["pods", "namespaces", "nodes", "secrets"]
  verbs: ["get", "list", "watch"]
- apiGroups: ["coordination.k8s.io"]
  resources: ["leases"]
  verbs: ["get", "create", "update"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: fleet-server
subjects:
- kind: ServiceAccount
  name: fleet-server
  namespace: elastic-system
roleRef:
  kind: ClusterRole
  name: fleet-server
  apiGroup: rbac.authorization.k8s.io
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: reveal-password-sa
  namespace: elastic-system
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: reveal-password-role
  namespace: elastic-system
rules:
- apiGroups: [""]
  resources: ["secrets", "pods"]
  verbs: ["get", "list", "watch"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: reveal-password-rb
  namespace: elastic-system
subjects:
- kind: ServiceAccount
  name: reveal-password-sa
  namespace: elastic-system
roleRef:
  kind: Role
  name: reveal-password-role
  apiGroup: rbac.authorization.k8s.io
