apiVersion: agent.k8s.elastic.co/v1alpha1
kind: Agent
metadata:
  name: synthetics-agent
  namespace: elastic-system
spec:
  version: 9.3.2
  fleetServerRef:
    name: fleet-server
  mode: fleet
  policyID: eck-synthetics-policy
  deployment:
    replicas: 1
    podTemplate:
      spec:
        securityContext:
          runAsUser: 0 
        containers:
          - name: agent
            env:
            - name: FLEET_INSECURE
              value: "true"
