[MikroTik-Router]
    enabled = True
    hostname = localhost
    port = 8728
    username = mktxp_user
    password = 
    use_ssl = False
    use_plain_text = True
[default]

# The section below contains the latest default parameters introduced by MKTXP
# For organizational purposes, you can move these parameters to the [default] section
[new_default_parameters]
    poe = True
    interface = True
    kid_control_dynamic = True
    container = False
    monitor = True
    bgp = True
    ipv6_route = False
    pool = True
    certificate = False
    route = True
    dns = True
    user = True
    w60g = False
    module_only = False
    no_ssl_certificate = False
    connections = True
    capsman_clients = True
    routing_stats = True
    dhcp = True
    enabled = False
    eoip = False
    ipv6_pool = False
    ssl_check_hostname = True
    health = True
    capsman = True
    netwatch = True
    lte = False
    switch_port = True
    wireless_clients = True
    use_ssl = False
    bfd = False
    ipsec = False
    gre = False
    queue = True
    public_ip = True
    firewall = True
    kid_control_assigned = True
    ssl_certificate_verify = False
    wireless = True
    plaintext_login = True
    ipv6_neighbor = False
    ipv6_firewall = False
    installed_packages = True
    ipip = True
    connection_stats = True
    neighbor = True
    dhcp_lease = True
    check_for_updates = True
    hostname = localhost
    username = user
    password = password
    credentials_file = ""
    ssl_ca_file = ""
    remote_dhcp_entry = None
    remote_capsman_entry = None
    address_list = None
    ipv6_address_list = None
    custom_labels = None
    interface_name_format = name
    port = 8728
